//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhino.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class amortizacion_por_mes
    {
        public long id { get; set; }
        public int cod_detalle_amortizacion { get; set; }
        public int pedido { get; set; }
        public string cod_articulo { get; set; }
        public string imei { get; set; }
        public System.DateTime mes_amortizar { get; set; }
        public Nullable<System.DateTime> mes_amortizado { get; set; }
        public Nullable<int> ano { get; set; }
        public Nullable<int> mescierre { get; set; }
        public int Estado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
        public Nullable<int> couta { get; set; }
        public Nullable<int> acumulado { get; set; }
    }
}
