//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhino.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class articulos_af
    {
        public int id { get; set; }
        public int codigo { get; set; }
        public string descripcion { get; set; }
        public string und { get; set; }
        public string cuenta { get; set; }
        public string tipo_iva { get; set; }
        public string grupo { get; set; }
        public int v_util { get; set; }
    }
}
