//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhino.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class bodegasst
    {
        public int id { get; set; }
        public string codigo { get; set; }
        public string marca { get; set; }
        public string referencia { get; set; }
        public string serial { get; set; }
        public string lote { get; set; }
        public Nullable<int> mes_fabricacion { get; set; }
        public Nullable<int> ano_fabricacion { get; set; }
        public Nullable<System.DateTime> f_compra { get; set; }
        public string proveedor { get; set; }
        public Nullable<int> tipo { get; set; }
        public string observaciones { get; set; }
        public int estado { get; set; }
        public string ccosto { get; set; }
        public string cedula_asig { get; set; }
        public Nullable<System.DateTime> f_prox_inspec { get; set; }
    }
}
