//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhino.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class como_dato
    {
        public int codigo { get; set; }
        public string estado { get; set; }
        public string placa { get; set; }
        public string serial { get; set; }
        public string usuario { get; set; }
        public string contrato { get; set; }
        public string cedula { get; set; }
        public string descripcion { get; set; }
        public string tercero { get; set; }
        public Nullable<int> valor { get; set; }
        public string ceco { get; set; }
        public string observacion { get; set; }
        public Nullable<System.DateTime> causacion { get; set; }
        public Nullable<System.DateTime> fecha_estado { get; set; }
    }
}
