//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhino.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class consecutivos
    {
        public int id { get; set; }
        public int consecutivo_ped { get; set; }
        public int consecutivo_srp { get; set; }
        public int consecutivo_rp { get; set; }
        public int consecutivo_as { get; set; }
        public Nullable<int> consecutivo_bd { get; set; }
    }
}
