//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhino.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class depreciacion_2021
    {
        public int id { get; set; }
        public int id_depre { get; set; }
        public string placa { get; set; }
        public string cuota { get; set; }
        public int mes_ult_eje { get; set; }
        public Nullable<int> enero { get; set; }
        public Nullable<int> febrero { get; set; }
        public Nullable<int> marzo { get; set; }
        public Nullable<int> abril { get; set; }
        public Nullable<int> mayo { get; set; }
        public Nullable<int> junio { get; set; }
        public Nullable<int> julio { get; set; }
        public Nullable<int> agosto { get; set; }
        public Nullable<int> septiembre { get; set; }
        public Nullable<int> octubre { get; set; }
        public Nullable<int> noviembre { get; set; }
        public Nullable<int> diciembre { get; set; }
    }
}
