//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhino.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class descuentos
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public string nombre { get; set; }
        public string cedula { get; set; }
        public string empresa { get; set; }
        public string valor_letras { get; set; }
        public decimal valor { get; set; }
        public int cuotas { get; set; }
        public string motivo { get; set; }
        public string usuario { get; set; }
        public int tipo_desc { get; set; }
        public string imei_articulo { get; set; }
        public string forma_desc { get; set; }
    }
}
