//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhino.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_devolucion
    {
        public int id_dev { get; set; }
        public string elemento { get; set; }
        public string marca { get; set; }
        public string placa_af { get; set; }
        public string estado { get; set; }
        public int cantidad { get; set; }
        public string observacion { get; set; }
        public string imei_inv { get; set; }
        public int c { get; set; }
        public int l { get; set; }
        public int a { get; set; }
        public int v { get; set; }
        public int f { get; set; }
    }
}
