//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhino.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_pedido_diff_acta
    {
        public int id { get; set; }
        public int id_pedido { get; set; }
        public Nullable<int> consecutivo { get; set; }
        public string cod_articulo { get; set; }
        public string usuario { get; set; }
        public int Estado { get; set; }
        public int EsPedidoLegalizado { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
    }
}
