//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhino.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_traslados
    {
        public int id { get; set; }
        public string ccosto_ini { get; set; }
        public string cuenta_ini { get; set; }
        public string rubro_ini { get; set; }
        public double disponible_ini { get; set; }
        public string ccosto_fin { get; set; }
        public string cuenta_fin { get; set; }
        public string rubro_fin { get; set; }
        public double disponible_fin { get; set; }
        public decimal valor_traslado { get; set; }
        public int id_presu_ini { get; set; }
        public int id_presu_fin { get; set; }
        public Nullable<int> ejecutado { get; set; }
        public int id_traslado { get; set; }
    }
}
