//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhino.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_depre
    {
        public int id_depreciacion { get; set; }
        public Nullable<int> id_pedido { get; set; }
        public string descripcion { get; set; }
        public string cuenta { get; set; }
        public Nullable<int> valor_activo { get; set; }
        public Nullable<System.DateTime> fecha_compra { get; set; }
        public Nullable<System.DateTime> fecha_ini_dep { get; set; }
        public Nullable<int> v_util { get; set; }
        public Nullable<int> depre_acumulada { get; set; }
        public Nullable<int> saldo_libros { get; set; }
        public Nullable<System.DateTime> fecha_ejecucion { get; set; }
        public Nullable<int> cuota { get; set; }
        public Nullable<int> v_util_restante { get; set; }
        public string rubro { get; set; }
        public Nullable<int> mes_ult_ejecucion { get; set; }
        public string placa_af { get; set; }
        public string ccosto { get; set; }
        public Nullable<int> baja { get; set; }
    }
}
