//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhino.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_rp
    {
        public int id { get; set; }
        public string nro_rp { get; set; }
        public string factura { get; set; }
        public System.DateTime fecha { get; set; }
        public string valor { get; set; }
        public string log_user { get; set; }
        public System.DateTime log_fecha { get; set; }
        public string log_hora { get; set; }
    }
}
