//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhino.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_usu_alt
    {
        public int id { get; set; }
        public int id_hv { get; set; }
        public int codigo { get; set; }
        public string cedula { get; set; }
        public string nombre { get; set; }
        public string cargo { get; set; }
        public Nullable<System.DateTime> f_entrega { get; set; }
        public Nullable<System.DateTime> f_devolucion { get; set; }
    }
}
