//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhino.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_pedido
    {
        public int id { get; set; }
        public int id_pedido { get; set; }
        public string codigo_art { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string und { get; set; }
        public Nullable<double> valor { get; set; }
        public Nullable<double> iva { get; set; }
        public Nullable<double> subtotal { get; set; }
        public Nullable<double> total { get; set; }
        public string cuenta { get; set; }
    }
}
