//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhino.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_act_sat
    {
        public int id { get; set; }
        public string ceco { get; set; }
        public string area { get; set; }
        public string area_funcional { get; set; }
        public string valor { get; set; }
        public string otros { get; set; }
        public string iva { get; set; }
        public string total { get; set; }
        public Nullable<int> consecutivo_as { get; set; }
    }
}
