//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhino.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        public int id { get; set; }
        public string cedula_emp { get; set; }
        public string nombre { get; set; }
        public string snombre { get; set; }
        public string ppellido { get; set; }
        public string spellido { get; set; }
        public string area { get; set; }
        public string cargo { get; set; }
        public int estado { get; set; }
        public int permiso { get; set; }
        public int ccosto { get; set; }
        public int empresa { get; set; }
    }
}
