//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhino.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa
    {
        public int id { get; set; }
        public string nit { get; set; }
        public string nombre { get; set; }
        public string codigo { get; set; }
        public string ruta_logo { get; set; }
        public int estado { get; set; }
    }
}
