//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhino.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class entrada_producto_diferido
    {
        public int id { get; set; }
        public int tipo { get; set; }
        public int pedido { get; set; }
        public string asignacion { get; set; }
        public string cod_articulo { get; set; }
        public string descripcion { get; set; }
        public string observacion { get; set; }
        public string ccosto { get; set; }
        public System.DateTime causacion { get; set; }
        public int Estado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string usuario { get; set; }
        public int EsProcesado { get; set; }
    }
}
