//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhino.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class inspec_escalera
    {
        public int id { get; set; }
        public string ced_empleado { get; set; }
        public string area { get; set; }
        public System.DateTime f_inspeccion { get; set; }
        public string idenfiticacion { get; set; }
        public string marca { get; set; }
        public Nullable<int> pasos { get; set; }
        public string fibra { get; set; }
        public string metalica { get; set; }
        public string uncuerpo { get; set; }
        public string doscuerpos { get; set; }
        public string descrip1 { get; set; }
        public string obs1 { get; set; }
        public string descrip2 { get; set; }
        public string obs2 { get; set; }
        public string descrip3 { get; set; }
        public string obs3 { get; set; }
        public string descrip4 { get; set; }
        public string obs4 { get; set; }
        public string descrip5 { get; set; }
        public string obs5 { get; set; }
        public string descrip6 { get; set; }
        public string obs6 { get; set; }
        public string descrip7 { get; set; }
        public string obs7 { get; set; }
        public string descrip8 { get; set; }
        public string obs8 { get; set; }
        public string descrip9 { get; set; }
        public string obs9 { get; set; }
        public string descrip10 { get; set; }
        public string obs10 { get; set; }
        public string descrip11 { get; set; }
        public string obs11 { get; set; }
        public string descrip12 { get; set; }
        public string obs12 { get; set; }
        public string descrip13 { get; set; }
        public string obs13 { get; set; }
        public string descrip14 { get; set; }
        public string obs14 { get; set; }
        public string descrip15 { get; set; }
        public string obs15 { get; set; }
        public string descrip16 { get; set; }
        public string obs16 { get; set; }
        public string descrip17 { get; set; }
        public string obs17 { get; set; }
        public string descrip18 { get; set; }
        public string obs18 { get; set; }
        public string descrip19 { get; set; }
        public string obs19 { get; set; }
        public string descrip20 { get; set; }
        public string obs20 { get; set; }
        public string descrip21 { get; set; }
        public string obs21 { get; set; }
        public string descrip22 { get; set; }
        public string obs22 { get; set; }
        public string descrip23 { get; set; }
        public string obs23 { get; set; }
        public string ced_usu_inspec { get; set; }
        public string ciudad { get; set; }
        public string respinspeccion { get; set; }
    }
}
