//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhino.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_usuario
    {
        public string hora { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string ventana { get; set; }
        public string accion { get; set; }
        public string codigo_usuario { get; set; }
        public decimal numero { get; set; }
        public int id { get; set; }
    }
}
