//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhino.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_user
    {
        public int id_transaccion { get; set; }
        public int tipo { get; set; }
        public int id_tipo { get; set; }
        public System.DateTime fecha { get; set; }
        public string hora { get; set; }
        public int id_usuario { get; set; }
    }
}
