//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhino.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class objeto
    {
        public int id { get; set; }
        public int tipo { get; set; }
        public string af { get; set; }
        public string imei { get; set; }
        public string descripcion { get; set; }
        public string observacion { get; set; }
        public int estado { get; set; }
        public string factura { get; set; }
        public string linea { get; set; }
        public string linea_activa { get; set; }
        public string valor { get; set; }
        public string nuevo_imei { get; set; }
        public Nullable<System.DateTime> causacion { get; set; }
        public string centro_costo { get; set; }
        public Nullable<System.DateTime> fecha_estado { get; set; }
        public Nullable<int> tipo_articulo { get; set; }
        public string cod_articulo { get; set; }
    }
}
