//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhino.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidos
    {
        public int id { get; set; }
        public int nro_pedido { get; set; }
        public System.DateTime fecha { get; set; }
        public string usuario { get; set; }
        public string proveedor { get; set; }
        public string ccosto { get; set; }
        public string justificacion { get; set; }
        public string vlr_total { get; set; }
        public Nullable<int> vto_bueno_presu { get; set; }
        public Nullable<System.DateTime> fecha_vto_bueno { get; set; }
        public Nullable<int> vto_bueno_finan { get; set; }
        public Nullable<System.DateTime> fecha_vto_finan { get; set; }
        public string estado { get; set; }
        public Nullable<int> nro_srp { get; set; }
        public Nullable<int> nro_rp { get; set; }
        public string nro_contrato { get; set; }
        public string obs_compras { get; set; }
        public string pc { get; set; }
        public string st { get; set; }
        public string et { get; set; }
        public string cont { get; set; }
        public string ad { get; set; }
        public string asignado_a { get; set; }
        public string aprobado_jefe { get; set; }
    }
}
