//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhino.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidos_tiempo_diff
    {
        public int id { get; set; }
        public int id_pedido { get; set; }
        public string cod_articulo { get; set; }
        public int tiempo { get; set; }
        public int estado { get; set; }
        public System.DateTime fechaCreacion { get; set; }
    }
}
