//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhino.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido_diferido_tiempo
    {
        public int id { get; set; }
        public int id_pedido { get; set; }
        public string cod_articulo { get; set; }
        public Nullable<int> consecutivo { get; set; }
        public Nullable<int> tiempo_amortizar { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_final { get; set; }
        public int EsPedidoLegal { get; set; }
        public int estado { get; set; }
        public string usuario { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
        public Nullable<int> EsPedidoPresupuesto { get; set; }
    }
}
