//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhino.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class permisos_usu
    {
        public int id_view { get; set; }
        public int id_usuario { get; set; }
        public string usuario { get; set; }
        public string autorizacion { get; set; }
        public string pe1 { get; set; }
        public string pe2 { get; set; }
    }
}
