//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhino.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class planillas_nomina
    {
        public int id { get; set; }
        public int consecutivo { get; set; }
        public string log_user { get; set; }
        public string estado { get; set; }
        public string ruta { get; set; }
        public System.DateTime fecha { get; set; }
    }
}
