//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhino.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class presupuesto
    {
        public int id { get; set; }
        public string ano { get; set; }
        public string cuenta { get; set; }
        public string rubro { get; set; }
        public string ccosto { get; set; }
        public double enero { get; set; }
        public double febrero { get; set; }
        public double marzo { get; set; }
        public double abril { get; set; }
        public double mayo { get; set; }
        public double junio { get; set; }
        public double julio { get; set; }
        public double agosto { get; set; }
        public double septiembre { get; set; }
        public double octubre { get; set; }
        public double noviembre { get; set; }
        public double diciembre { get; set; }
        public double total_presupuesto { get; set; }
        public double total_ejecucion { get; set; }
        public double disponibilidad { get; set; }
        public string indice { get; set; }
    }
}
