//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhino.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedor
    {
        public int id { get; set; }
        public string nit { get; set; }
        public string razon_social { get; set; }
        public string representante_legal { get; set; }
        public string tel { get; set; }
        public string asesor { get; set; }
        public string correo { get; set; }
        public string tel_asesor { get; set; }
        public string contrato { get; set; }
        public int estado { get; set; }
    }
}
