//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhino.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class srp
    {
        public int id { get; set; }
        public int id_pedido { get; set; }
        public string ccosto { get; set; }
        public string cuenta { get; set; }
        public Nullable<double> total { get; set; }
        public int comprobado { get; set; }
        public string rubro { get; set; }
        public string grupo { get; set; }
        public Nullable<int> v_util { get; set; }
        public Nullable<int> saldo_pdte { get; set; }
    }
}
