//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhino.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_detalle_presiones
    {
        public int id { get; set; }
        public int id_presion { get; set; }
        public int id_presupuesto { get; set; }
        public string ccosto { get; set; }
        public string cuenta { get; set; }
        public string rubro { get; set; }
        public decimal valor { get; set; }
    }
}
