//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhino.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class views
    {
        public int id { get; set; }
        public string name_module { get; set; }
        public string module { get; set; }
        public string icon { get; set; }
        public string url { get; set; }
        public string visible { get; set; }
    }
}
